Add initial zones documentation for end users
solidusio/solidus pull request #2750
Opened 2018-05-29 00:11 UTC by benjaminwil

This PR is blocked by #2719.

This adds initial documentation about Solidus's zones settings for end users. The audience for this documentation is store administrators or anyone who has to touch the solidus_backend as a business person.

2018-05-29 17:58 UTC, gmacdougall requested changes

2018-05-29 20:28 UTC, benjaminwil commented on guides/source/users/settings/zones.html.md
> +Canada, but you use FedEx to ship to the United States and Canada as well as to
I'm not sure how this example would be applied to shipping in a zones context. But I do agree that this example should be added elsewhere.

The example here that I am providing is generic but clear.

2018-06-05 07:57 UTC, tvdeyen requested changes
One typo.

2018-06-05 07:57 UTC, tvdeyen commented on guides/source/developers/locations/zones.html.md
> +specific places. They also allow you group states or countries in a
> They also allow you group states

Missing "to"

2018-06-07 07:57 UTC, tvdeyen approved these changes

2018-06-13 14:40 UTC, gmacdougall approved these changes

2018-06-29 13:34 UTC, merged