Add promotion actions and promotion calculators documentation for end users
solidusio/solidus pull request #2755
Opened 2018-05-30 21:51 UTC by benjaminwil

This adds documentation about Solidus's promotion actions and calculators for end users. The audience for this documentation is store administrators or anyone who has to touch the solidus_backend as a business person.

2018-06-02 18:11 UTC, kennyadsl approved these changes
Thanks!

2018-06-07 08:10 UTC, tvdeyen requested changes
The promotion calculators table header should be improved. Other than that 👍

2018-06-07 08:10 UTC, tvdeyen commented on guides/source/users/promotions/promotion-calculators.html.md
> +Depending on the [type of promotion action][promotion-action-types] that you are
missing link

2018-06-07 08:10 UTC, tvdeyen commented on guides/source/users/promotions/promotion-calculators.html.md
> +When you create a promotion action, one step is to select the promotion
Maybe add a short sentence what a calculator does. It's often not clear for non technical people what this thing is for, besides that it 'calculates things'.

2018-06-07 08:10 UTC, tvdeyen commented on guides/source/users/promotions/promotion-calculators.html.md
> +promotion action types they can be applied to:
The header of this table is misleading. There are no promotion action types listed, these are calculables (a term we probably should explain as well).

2018-06-12 17:56 UTC, benjaminwil commented
@tvdeyen Thank you for the feedback. I think my most recent commit addresses all your comments.

2018-06-12 18:46 UTC, tvdeyen reviewed
One small typo. But this good to go then

2018-06-12 19:35 UTC, tvdeyen approved these changes

2018-06-12 19:35 UTC, merged