Add initial shipments documentation for end users
solidusio/solidus pull request #2784
Opened 2018-06-26 22:55 UTC by benjaminwil

This adds documentation about the Solidus shipping interface for end users. The audience for this documentation is store administrators or anyone who has to touch the `solidus_backend` as a business person.

It also changes some of the English translation strings for the backend interface, which is a minor UX improvement.

2018-10-05 22:50 UTC, tvdeyen reviewed
Would love to have this in. There is a yaml syntax error causing the tests to fail. Would you mind fixing it?

2018-10-05 22:50 UTC, tvdeyen commented on core/config/locales/en.yml
> +        code: "An identifier for your store. Developers may need this value if you operate multiple storefronts.
Missing double quotes at the end of this line causes nearly all tests to fail.

2018-10-05 22:50 UTC, tvdeyen commented on backend/app/views/spree/admin/shipping_methods/_form.html.erb
> +  <div data-hook="admin_shipping_method_form_admin_name_field" class="col-5">
We should not change the data-hook attribute. Stores might have used Deface to override the view.

2018-10-05 23:30 UTC, benjaminwil commented
Fixed! Sorry about that.

2018-10-15 15:40 UTC, ericsaupe requested changes
Looks good! Would you mind squashing your commits?

I'm not sure if the spec failures are related to a fix that was recently pushed to `master` but it might be a good idea to rebase just to be sure.

Thanks!

2018-11-23 01:48 UTC, jacobherrington approved these changes
Is this something we still plan to get in? It looks good to me.

2018-11-23 15:46 UTC, ericsaupe approved these changes
Looks good to me!

2019-02-08 16:56 UTC, kennyadsl commented
Closing, I'm reopened this into #3092. Thanks anyway @benjaminwil!

2019-02-08 16:56 UTC, closed without merging

2019-02-08 17:36 UTC, benjaminwil commented
No problem. Didn't intend to abandon this, and I fixed that YML – why couldn't we merge it?

2019-02-08 17:47 UTC, kennyadsl commented
There was a conflict in the yml file yet so it couldn't allow me to merge. No worries, you have the owership of the commits in the PR I just open, so it does not change much. Thanks again!