Improve Solidus events documentation
solidusio/solidus pull request #3819
Opened 2020-10-30 09:52 UTC by spaghetticode

**Description**

Solidus internal events were not showing properly.

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [x] I have updated Guides and README accordingly to this change (if needed)

2020-11-04 10:57 UTC, kennyadsl approved these changes

2020-11-04 11:11 UTC, aldesantis requested changes

2020-11-04 11:11 UTC, aldesantis commented on guides/source/developers/events/overview.html.md
> +You can subscribe to events also by creating a "subscriber" module that includes
This should be "You can _also_ subscribe to events _by_ creating a "subscriber" module".

2021-04-23 15:53 UTC, aldesantis approved these changes

2021-04-23 15:54 UTC, merged