Rename currently_valid to prioritized_for_default
solidusio/solidus pull request #4109
Opened 2021-06-21 03:55 UTC by waiting-for-dev

**Description**

It conveys better what it's doing, as the query only consists of `ORDER`
clauses and no record is filtered out.

Extracted from #3994

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [ ] I have updated Guides and README accordingly to this change (if needed)
- [ ] I have added tests to cover this change (if needed)
- [ ] I have attached screenshots to this PR for visual changes (if needed)

2021-06-21 08:49 UTC, kennyadsl requested changes
Nice, but I think we need some deprecations here.

2021-06-21 08:49 UTC, kennyadsl commented on core/app/models/concerns/spree/default_price.rb
> -    def currently_valid_prices
I think we should deprecate this method instead of removing it.

2021-06-21 08:49 UTC, kennyadsl commented on core/app/models/spree/price.rb
> -    scope :currently_valid, -> { order(Arel.sql("country_iso IS NULL")).order(updated_at: :DESC, id: :DESC) }
Let's deprecate this as well!

2021-08-05 07:29 UTC, waiting-for-dev commented
We're closing it as we'll be revisiting this stuff in the context of services objects.

2021-08-05 07:29 UTC, closed without merging