Rename files in api/spec/requests/spree/api and in api/spec/controllers/spree/api
solidusio/solidus pull request #4122
Opened 2021-06-27 14:50 UTC by AymanJabr

In this PR I attempt to solve Issue #4001. This Issue is a follow up to PR #2052, where API controller specs have been converted to request specs.

The issue is about cleaning up references to controllers from the previous PR. This is mostly in the file names.

Since this is my first contribuition to an open project, it is a good Issue to try and fix. I did have some issues while trying to understand how everything fit toghether though, and I try to explain these issues below.

The first issue that I have with this Issue is that most of the files changed in the previous PR are not in the original (api/spec/controllers/spree/api/) path. Even the file called addresses_controller_spec.rb, given as an example by @Kennyadsl is not there anymore. This is the case both for the master branch and for the latest v3.0 branch.
However these files can be found elsewhere in the repo, for example, address_controller_spec.rb can be found in api/spec/requests/spree/api/. This change in files is to be expected since this is what the Rspec docs recommend (API specs are in the requests folder): https://relishapp.com/rspec/rspec-rails/docs/directory-structure

@Niamtokik asks how he should name the new files in the Issue, @Kennyadsl responds by saying that it should be done according to Rails convention. From what I am seeing in the example given in the docs for Request type spec: https://relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec. The name of the file does not contain _request_ in the middle, so a file named "addresses_controller_spec.rb" would become "addresses_spec.rb". Am I right in this assessment? Should I name the files according to some other convention?

The second part of @Kennyadsl Issue request says to "clean-up references inside the specs", and he gives this as an example: 
```
module Spree
  describe Api::AddressesController, type: :request do
```

This part has me a bit confused because the specs are still referring to the controllers, so the spec for AddressesController is still referring to that class. @Niamtokik asks him if he should rename the spec such as "AddressRequest". @Jarednorman tells him that this wouldn't work, because such classes do not exist, and the spec would not know where to look for them. Is this a misunderstanding from @Kennyadsl? Or should the Controllers themselves be named differently? In the case of the latter, should I open a new Issue and ask for someone to rename the controllers?

Lastly, out of the 35 commits made by @Jhawthorn, most of them do not reference the controllers, except for the file name. Am I missing something? Are there more details that I should change/remove?

2021-07-04 21:56 UTC, jarednorman commented
When I say the constant doesn't exist, it is because in [this comment](https://github.com/solidusio/solidus/issues/4001#issuecomment-821866925), @niamtokik suggests changing:

```ruby
module Spree
  describe Api::AddressesController, type: :request do
  # ...
```

to this:

```ruby
module Spree
  describe Api::AddressesRequest, type: :request do
  # ...
```

`Spree::Api::AddressesController` is a constant that exists; `Spree::Api::AddressesRequest` does not.

This PR addresses the file naming issue, so I'm happy with it as an incremental improvement, but we've not yet addresses the naming convention issue within the files: these are request specs and so likely shouldn't explicitly reference the controller they are testing.

2021-07-04 21:56 UTC, jarednorman approved these changes

2021-07-05 09:15 UTC, kennyadsl requested changes
Thanks! 🙏 

I think that `api/spec/controllers/spree/api/base_controller_spec.rb`, `api/spec/controllers/spree/api/resource_controller_spec.rb` and `api/spec/controllers/spree/api/soft_deletable_resource_controller_spec.rb` may not need a rename. Or is it a good practice to remove the `_controller` part from controller specs as well? Reading [this page](https://relishapp.com/rspec/rspec-rails/docs/controller-specs/controller-spec), looks like it's a good practice to keep it, isn't it?

I second what @jarednorman said: using a call that does not exist in the main `describe` block is not ideal, [see here for some example](https://relishapp.com/rspec/rspec-rails/v/5-0/docs/request-specs/request-spec).

2021-07-20 12:26 UTC, kennyadsl commented
Closing, thanks anyway!

2021-07-20 12:26 UTC, closed without merging