Fix gateway_error when no order is defined
solidusio/solidus pull request #4156
Opened 2021-08-31 21:44 UTC by alexblackie

If the current controller raises a gateway error, but does not have
`@order` defined, this error handler will raise a NoMethodError when it
tries to access `nil.errors`.

We can resolve this by falling back to an empty Order instance if none
is defined. This maintains the existing behaviour, and as the response
only serializes the errors hash, there shouldn't be any surprises with
null fields, etc.

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [x] I have added tests to cover this change (if needed)

2021-08-31 21:51 UTC, jarednorman requested changes

2021-08-31 21:51 UTC, jarednorman commented on api/spec/controllers/spree/api/base_controller_spec.rb
> +    context "with @order not defined" do
Are your contexts backwards?

2021-08-31 21:52 UTC, alexblackie commented on api/spec/controllers/spree/api/base_controller_spec.rb
> +    context "with @order not defined" do
.......

2021-09-01 07:57 UTC, kennyadsl commented
Thanks, @alexblackie! Just to add some context, in which circumstances can this happen? I saw the specs but with a standard checkout flow it's very unlikely that we'll have an exception related to the gateway in a controller that is not related to the checkout where, I guess, having an order is mandatory.

2021-09-01 15:51 UTC, alexblackie commented
@kennyadsl Ah yeah, for context, this was raised in a custom reimbursements API controller, which interacts with payments (refunds) but does not have an `@order`.

Since the `:authorize_for_order` filter is conditional on params, there is no guarantee `@order` will be set even in Core controllers, unless the child controller assigns it. Also from an architecture/abstraction point of view it seems wrong to have a `rescue_from` in a base controller make assumptions about pre-existing internal state, especially if that state came from a child.

2021-09-01 16:55 UTC, jarednorman approved these changes
Makes sense to me. Thanks, Alex!

2021-09-08 11:20 UTC, kennyadsl commented
> Also from an architecture/abstraction point of view it seems wrong to have a rescue_from in a base controller make assumptions about pre-existing internal state, especially if that state came from a child.

Agree, thanks for sharing the context!

2021-09-08 11:21 UTC, kennyadsl approved these changes

2021-09-08 11:21 UTC, merged