Fix loading core on Rails < 6.1
solidusio/solidus pull request #4179
Opened 2021-09-27 09:27 UTC by waiting-for-dev

**Description**

To avoid warning about `Spree.load_defaults` not being defined at a
moment when `bin/rails g solidus:install` has not even been called, the
`Spree::Core` engine is checking whether the `spree.rb` initializer
already exists (as it's there where `#load_defaults` should be called).

We're looking for `spree.rb` within the directories associated with the
`Rails::Paths::Path` instance for initializers. However, before this
commit, we were using `Rails::Paths::Path#paths` method, which is only
available on Rails >= 6.1.0. That made the loading of `Spree::Core`
crash.

As `Rails::Paths::Path` is an `Enumberable`, we can use `any?` directly
from the instance and manually build the `Pathname` for each yielded
string instead.

We also added tests to cover the previous failure and changed the naming
to make the purpose clearer.

Fixes #4178

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [ ] I have updated Guides and README accordingly to this change (if needed)
- [x] I have added tests to cover this change (if needed)
- [ ] I have attached screenshots to this PR for visual changes (if needed)

2021-09-27 20:44 UTC, jarednorman approved these changes

2021-09-27 23:03 UTC, AlistairNorman requested changes
Thanks for fixing this!

2021-09-27 23:03 UTC, AlistairNorman commented on core/lib/spree/core.rb
> +      rails_paths['config/initializer'].any? do |path|
```suggestion
      rails_paths['config/initializers'].any? do |path|
```

I think `initializers` needs to be pluralized, that's why CI is failing.

2021-09-28 15:35 UTC, AlistairNorman approved these changes

2021-09-28 16:39 UTC, jarednorman approved these changes

2021-09-28 16:44 UTC, kennyadsl approved these changes
Thanks @waiting-for-dev and @AlistairNorman for reporting and reviewing accurately. 🤝

2021-09-28 16:45 UTC, merged