Remove Spree::Order#add_default_payment_from_wallet checkout transition
solidusio/solidus pull request #4185
Opened 2021-09-29 09:30 UTC by danielpuglisi

This PR is still work in progress.

I'm currently building a shop with solidus and found some logic that seems unnecessary that originated from a 7 year old PR from before the fork: https://github.com/spree/spree/pull/5148

The current behaviour is this:

1. A user with an existing payment source transitions from `delivery` to `payment` state
2. [Spree::Order#add_default_payment_from_wallet](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/order.rb#L686-L698) gets triggered by the [state machine](https://github.com/solidusio/solidus/blob/master/core/lib/spree/core/state_machines/order.rb#L85).
3. User transitions to `confirm` state
4. Through how the checkout logic works with [Spree::OrderUpdateAttributes](https://github.com/codegestalt/solidus/blob/ec4bdf33325d29ca4243dbccfd699c628b4a9576/core/app/models/spree/order_update_attributes.rb#L35-L39), that default payment does not get reused and is always replaced with a new payment, resulting every time in an invalid payment record:

![image](https://user-images.githubusercontent.com/507849/135239652-ffc98aff-f003-43ae-b4b3-140f829ba481.png)

My expectations would be one of the following:

1. The default payment record has some kind of use (so far I haven't found one) and gets updated instead of invalidated (I'm also not sure how this affects fraud detection)
2. No default payment gets created as it has no use

So I started this PR by removing `Spree::Order#add_default_payment_from_wallet` to see what breaks. So far only those removed in this [commit](https://github.com/codegestalt/solidus/commit/ec4bdf33325d29ca4243dbccfd699c628b4a9576#diff-c2434636d311e5db5ab103cdd58bd3f44b947d4d384525b6d0c4c475adf1b1ad) have been affected but it seems to me that these are directly tied to the creation of the default payment source and have no further use. The only spec I'm unsure about is the one about assigning a billing address if none exists yet, but I can't think of a scenario where this should be the case.

Another thing the removal of `Spree::Order#add_default_payment_from_wallet` would affect is that it makes [Spree::Wallet::DefaultPaymentBuilder](https://github.com/solidusio/solidus/blob/master/core/app/models/spree/wallet/default_payment_builder.rb) obsolete. So I guess there is a concern about breaking compatibility with existing shops that rely on that one. Although I'm not sure what a use case could be.

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [ ] I have updated Guides and README accordingly to this change (if needed)
- [ ] I have added tests to cover this change (if needed)
- [ ] I have attached screenshots to this PR for visual changes (if needed)

2021-09-29 22:54 UTC, jarednorman commented
This is related to #2680.

2021-09-29 23:22 UTC, adammathys requested changes
This generally seems reasonable to me. (Removing the `add_default_payment_from_wallet` method.) I can't see any reason why we would ever want that extra invalid payment and we're always going to create a new one during the payment step of checkout.

I think we should probably start by deprecating the method instead of outright removing it. (Along with maybe deprecating the `Spree::Config.default_payment_builder_class` config option and corresponding class.) Just in case there's anyone out there relying on this behaviour for some reason.

Then we could add a new configuration option to skip this callback step for everyone ready to remove this functionality ahead of it being removed in a future release. e.g.:
```ruby
unless Spree::Config.disable_adding_default_payment_to_order
  before_transition to: :payment, do: :add_default_payment_from_wallet
end
```

2021-09-30 07:22 UTC, danielpuglisi commented
@adammathys makes sense. If there are no other concerns, I'll gladly put something together.

2021-10-01 20:27 UTC, jarednorman commented
Thanks @danielpuglisi (and @adammathys), that would be great!

2021-12-14 15:42 UTC, danielpuglisi commented
Finally got the time to take a jab at this.

Added the deprecation preference and warnings based on @adammathys suggestion. The current default preference although creates a lot of noise when running the specs. What is the preferred way to handle this?

2022-06-13 07:22 UTC, waiting-for-dev commented
We appreciate your contribution, @danielpuglisi. After talking with @kennyadsl, we decided to put it on hold for the meantime. It looks like a legit change, although it's entirely possible it'd break some extensions. We feel we need to define a clear path for the evolution of the payment system before introducing more changes.

2022-06-13 11:15 UTC, danielpuglisi commented
I understand. Let me know if I can be of any help in the future.

2022-08-23 09:17 UTC, kennyadsl commented
Hey @danielpuglisi, first of all thanks for the PR and sorry for taking so long to come back on this. We'd love to move this forward because this is annoying on all levels (Admin UX and for the developer). 

We have a couple of things left to do before we can merge this:

1. Rebase the PR against master
2. Change the preference usage to use the new [versioned preferences](https://github.com/solidusio/solidus/blob/9948b01d0e7ec3b77c6aab6421c52adc37be765d/core/lib/spree/preferences/configuration.rb#L129-L151) ([here](https://github.com/solidusio/solidus/blob/3479d43660330be75ba6774dfc1db426a5c9ca13/core/lib/spree/app_configuration.rb#L297) you can find a usage example).
3. run specs of a couple of payment gateway extensions against the local version of solidus that contains this change. I suggest to try with [solidus_stripe](https://github.com/solidusio/solidus_stripe) and [solidus_paypal_braintree](https://github.com/solidusio/solidus_paypal_braintree), which are the most used. 


Please let us know if you have time to take care of these last things otherwise, we will happily take over this work as soon as we have some availability. 

Thanks again! 🙏

2022-08-29 11:07 UTC, danielpuglisi commented
Hey @kennyadsl. I'm a bit flooded right now. Feel free to take over if you get the time and I haven't done anything.

2026-08-31 23:38 UTC, jarednorman commented
I'm closing this in favour of #6564. @adammathys is working on broadly improving how payments are handled and this approach is incompatible with his, (besides being suuuuper stale). With payment reuse, we don't need to remove `add_default_payment_from_wallet`. The transition will do what it intends to do.

2026-08-31 23:38 UTC, closed without merging