Fix Frontend scss font url import
solidusio/solidus pull request #4209
Opened 2021-11-24 09:22 UTC by RyanofWoods

Since 23/11/2021, this line started to cause errors. Breaking Solidus
and all extensions that depend on solidus_frontend.

Error example:
https://app.circleci.com/pipelines/github/solidusio/solidus/2791/workflows/e62ff646-9ae6-4e65-b20f-e1f7a109d3a1/jobs/26572

**Checklist:**
- [x] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [x] I have added a detailed description into each commit message
- [ ] I have updated Guides and README accordingly to this change (if needed)
- [ ] I have added tests to cover this change (if needed)
- [ ] I have attached screenshots to this PR for visual changes (if needed)

2021-11-24 09:39 UTC, RyanofWoods commented
I am not really sure why this line suddenly started causing issues. Would be interested to know if anyone has any insight.

2021-11-24 10:59 UTC, waiting-for-dev requested changes
Many thanks for looking into it @RyanofWoods! :heart: 

I haven't found anything out there, but I guess that since that date, `fonts.googleapis.com` doesn't support non-SSL connections anymore. Anyway, it's good from our side to request through `HTTPS`.

I think we also need to update the URL here:

https://github.com/solidusio/solidus/blob/e878076f2ed670d07654ab6293a16588743f2fa6/core/lib/spree/testing_support/blacklist_urls.rb#L8

I'd also take the occasion to remove the duplication from this line:

https://github.com/solidusio/solidus/blob/d4925d83ef619c1a752c1f5f4f00e9597dd07510/backend/spec/spec_helper.rb#L100

And instead require `spree/testing_support/blacklsit_urls` as is done from the frontend engine:

https://github.com/solidusio/solidus/blob/d4925d83ef619c1a752c1f5f4f00e9597dd07510/frontend/spec/spec_helper.rb#L39

2021-11-24 11:40 UTC, waiting-for-dev commented on backend/spec/spec_helper.rb
> -    Rails.cache.clear
We should not remove this line, right?

2021-11-24 12:06 UTC, RyanofWoods commented on backend/spec/spec_helper.rb
> -    Rails.cache.clear
I think not 👍 I added it back now.

2021-11-24 12:12 UTC, waiting-for-dev approved these changes
Thanks @RyanofWoods :raised_hands: :raised_hands:

2021-11-24 13:27 UTC, RyanofWoods commented
> Thanks @RyanofWoods 🙌 🙌

Thank you for your help @waiting-for-dev! Amazing spot with the `testing_support` 🙌

2021-11-24 16:14 UTC, gmacdougall approved these changes

2021-11-24 16:14 UTC, jarednorman approved these changes

2021-11-24 16:16 UTC, kennyadsl approved these changes
👍

2021-11-24 16:16 UTC, spaghetticode approved these changes
@RyanofWoods thank you 👍

2021-11-25 05:37 UTC, merged

2021-11-25 08:13 UTC, kennyadsl commented
@RyanofWoods thanks! I think we need to release this in all the supported Solidus versions as well. Can you make the same PR against [v3.1](https://github.com/solidusio/solidus/tree/v3.1), [v3.0](https://github.com/solidusio/solidus/tree/v3.0) and [v2.11](https://github.com/solidusio/solidus/tree/v2.11), please?

2021-11-25 10:06 UTC, RyanofWoods commented
> @RyanofWoods thanks! I think we need to release this in all the supported Solidus versions as well. Can you make the same PR against [v3.1](https://github.com/solidusio/solidus/tree/v3.1), [v3.0](https://github.com/solidusio/solidus/tree/v3.0) and [v2.11](https://github.com/solidusio/solidus/tree/v2.11), please?

Done @kennyadsl 👍 Let me know if I could have done it in a more helpful way 🙂