fix backbone shipment item view when split
solidusio/solidus pull request #4250
Opened 2022-01-26 04:43 UTC by ccarruitero

This PR is sponsored by [MagmaLabs](https://www.magmalabs.io/)

**Description**
This will fix current build for `solidus_product_assembly` https://app.circleci.com/pipelines/github/solidusio-contrib/solidus_product_assembly/194/workflows/a9e6929f-4d14-4234-bdcf-5266a359875a/jobs/464

Since we updated to use jquery3 in https://github.com/solidusio/solidus/commit/bdfa09409477d94198f5db96605600b93f066ef8, we need to update ajax callback to avoid use `success`, `error` and `complete` that are deprecated now https://api.jquery.com/jquery.ajax/

**Checklist:**
- [X] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [ ] I have added a detailed description into each commit message
- [ ] I have updated Guides and README accordingly to this change (if needed)
- [ ] I have added tests to cover this change (if needed)
- [ ] I have attached screenshots to this PR for visual changes (if needed)

2022-01-31 04:07 UTC, waiting-for-dev commented
Should we add a regression test for that?

2022-02-02 16:18 UTC, kennyadsl commented
I second what @waiting-for-dev is asking. How didn't we notice that before? We are probably missing some specs for that part and if you could add it @ccarruitero, it would be great. Thanks!

2022-02-08 03:43 UTC, waiting-for-dev requested changes

2022-02-08 03:43 UTC, waiting-for-dev commented on backend/spec/features/admin/orders/shipments_spec.rb
> +describe "Shipments", type: :feature, js: true do
Can we add this only to the new test addition? Tests that use javascript are slower, so it's better not to affect all of them.

2022-02-08 03:43 UTC, waiting-for-dev commented on backend/spec/features/admin/orders/shipments_spec.rb
> +      sleep 5
We definitely should find a way to don't need to `sleep`. The reason is not making the suite slower.

2022-02-17 02:30 UTC, ccarruitero commented
@waiting-for-dev I just updated PR according your comments. Please take a look when you have a chance

2022-02-17 04:35 UTC, waiting-for-dev approved these changes
Thanks! :rocket:

2022-03-15 16:02 UTC, kennyadsl approved these changes
Thanks, this is probably worth for a backport.

2022-03-16 05:02 UTC, merged