Update README.md chromedriver link
solidusio/solidus pull request #4294
Opened 2022-03-04 12:45 UTC by Palid

The link for chromedriver is leading to a deprecated website that will get remove in the nearby future. 
This commit updates the link to a correct version.
NOTE: May not work with corporate-managed google chrome account (visit in private mode instead), just google things.

**Description**

**Checklist:**
- [ ] I have followed [Pull Request guidelines](https://github.com/solidusio/solidus/blob/master/CONTRIBUTING.md#pull-request-guidelines)
- [ ] I have added a detailed description into each commit message
- [ ] I have updated Guides and README accordingly to this change (if needed)
- [ ] I have added tests to cover this change (if needed)
- [ ] I have attached screenshots to this PR for visual changes (if needed)

2022-03-07 09:50 UTC, waiting-for-dev requested changes

2022-03-07 09:50 UTC, waiting-for-dev commented on README.md
> +[ChromeDriver](https://sites.google.com/chromium.org/driver/) is
```suggestion
[ChromeDriver](https://chromedriver.chromium.org/downloads) is
```

It seems :point_up: won't give problems, right? I just googled it :man_shrugging:

2022-03-09 19:50 UTC, jarednorman commented
Should we be using the [webdrivers gem](https://github.com/titusfortner/webdrivers)?

2022-06-07 09:57 UTC, waiting-for-dev commented
Hey @Palid :wave: What do you think about the [given suggestion](https://github.com/solidusio/solidus/pull/4294#discussion_r820538767)?

2022-06-14 09:03 UTC, waiting-for-dev approved these changes

2022-06-14 09:04 UTC, waiting-for-dev commented
I updated the suggestion myself. We need one more approval to get it merged cc @jarednorman @kennyadsl

2022-06-14 12:06 UTC, merged