Add a deprecation warning for allow_promotions_any_match_policy = true
solidusio/solidus pull request #4991
Opened 2023-03-22 08:36 UTC by kennyadsl

## Summary

We are going to remove this preference in Solidus 4.0, along with the possibility to create promotion rules with the "Any" match policy. 

The only accepted value for those who want to upgrade is `false`.

Ref https://github.com/solidusio/solidus/pull/4304

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [ ] I have written a thorough PR description.
- [ ] I have kept my commits small and atomic.
- [ ] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

2023-03-22 08:43 UTC, waiting-for-dev approved these changes

2023-03-22 08:57 UTC, RyanofWoods requested changes

2023-03-27 09:22 UTC, kennyadsl commented on core/lib/spree/app_configuration.rb
> +      if allow_promotions_any_match_policy == true
Done!

2023-03-27 15:08 UTC, adammathys approved these changes

2023-03-29 03:21 UTC, waiting-for-dev approved these changes

2023-03-29 07:50 UTC, merged