Dp/improve promotion code batch
solidusio/solidus pull request #5383
Opened 2023-09-14 14:36 UTC by DanielePalombo

## Summary

When a new promotion with 2.5m new promo codes has created, it just generated about 250k promo codes and then stopped.

The PromotionBatch screen this error: Errored: #<ActiveRecord::RecordInvalid: Validation failed: Value has already been taken>
Solidus Promotion: https://lmn-eagle.herokuapp.com/admin/promotions/863865/edit

This PR rescues the exception raised by the Spree::PromotionCode creation and jumps to the next code to save, avoiding stopping the process completely.
The PR also adds the ability to restart the PromotionCodeBatch from the latest PromotionCodes created.

Fixes: https://github.com/solidusio/solidus/issues/5379

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [X] I have written a thorough PR description.
- [X] I have kept my commits small and atomic.
- [X] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.
- 📑 I have documented new code [with YARD](https://www.rubydoc.info/gems/yard/file/docs/Tags.md).
- 🛣️ I have opened a PR to update the [guides](https://github.com/solidusio/edgeguides).
- ✅ I have added automated tests to cover my changes.
- 📸 I have attached screenshots to demo visual changes.

2023-11-08 13:19 UTC, tvdeyen reviewed
What happens if we never reach the number of codes needed? The validation might fail consistently and we will end up in an infinite loop, no?

2023-11-08 13:19 UTC, tvdeyen commented on core/app/models/spree/promotion_code/batch_builder.rb
> +      codes_for_current_batch = codes_for_current_batch.map do |value|
collecting results of large code counts can exceed available memory pretty quickly.

2023-11-13 18:35 UTC, jarednorman requested changes

2023-11-13 18:35 UTC, jarednorman commented on core/app/models/spree/promotion_code/batch_builder.rb
> +      end.compact
To address @tvdeyen's concern, what about something like:

```ruby
codes_for_current_batch.filter! do |value|
  Spree::PromotionCode.create!(
    value: value,
    promotion: promotion,
    promotion_code_batch: promotion_code_batch
  )
rescue ActiveRecord::RecordInvalid
  false
end
```

This should maintain the existing performance characteristics.

2025-01-08 21:58 UTC, forkata commented
@jarednorman I believe your recommendations were addressed as part of https://github.com/solidusio/solidus/pull/5830, so this PR can now be closed?

2025-01-09 23:21 UTC, closed without merging