Bumped license years and added font license
solidusio/solidus pull request #5948
Opened 2024-11-20 16:54 UTC by fthobe

## Summary

The license file was not aligned with the legal requiremenets of the assets contained in the repo. 

## Modifications made
Aligned license.md with reality: 
- added icon license (required by the icon license)
- added solidus own FreeBSD license
- bumped year of the license to 2024

Fixes: #5947 and bumps FreeBSD license to current year

2024-11-21 02:45 UTC, jarednorman requested changes
IANAL and am unsure of best practices around this.

On the RemixIcon license: My gut tells me we should include the licenses as separate files, but I'd love to see examples of what other projects do here. I'm also curious if we need to have these icons included in the repo itself at all, or if they can be included via a package, rendering the licensing issue moot.

On the change of the Solidus license: "solidus.io" is not a legal entity and can't hold a copyright and I don't know what right we have to change the license anyway (even if the only change is the copyright holders).

It says right there in the existing license, "Redistributions of source code must retain the above copyright notice". We can't just change that. That's not how software licensing works.

2024-11-21 06:51 UTC, tvdeyen commented
Regarding the remix icon license. Good practice is to put it right beside where the icon file lives. Definitely not inside our license file. 

Regarding the solidus vs. spree license. My gut tells me to have two separate files, but I would like to see examples of how other forks of open source software handled this in the past before we make any decisions. 

*) Obvious IANAL disclaimer

2024-11-21 10:24 UTC, fthobe commented
> Regarding the remix icon license. Good practice is to put it right beside where the icon file lives. Definitely not inside our license file. 
> 

This is TBH personal preference and I feel absolutely ok with both. How about I make a pull request just for that as we all seem to have common ground here.

> Regarding the solidus vs. spree license. My gut tells me to have two separate files, but I would like to see examples of how other forks of open source software handled this in the past before we make any decisions. 
> 
> *) Obvious IANAL disclaimer

I would warmly suggest that there's a decision regarding the copyright party picking either of
- Collective 
- individual 
- association (eg a foundation)

I have to check very strictly due to external compliance requirements, but I have the feeling that compliance has been neglected a little on this repo. 

Surely no active copy right owner can't be right as long as the code is not public domain (which by force of the BSD license it is not). 

Just keep in mind that there are (might be interesting for you @jarednorman) forms of not incorporated associations (would be the nicht eingetragener Verein in Germany) and here the threshold might already be met given a clear code of conduct, but not for Italy for example. I know that right now I would not implement solidus (nor spree) for the given issues in our application stack (usually where there's smoke there's fire).

2024-11-21 23:02 UTC, jarednorman commented
"other contributors" covers all the other groups of people that contribute to Solidus, and so I believe we only need to update the dates on the existing license. Spree Commerce Inc. (if the entity even still exists) retains the copyright of their contributions that still exist in the project.

```
Copyright © 2007-2024, Spree Commerce Inc. and other contributors.
```

2024-11-22 23:20 UTC, fthobe commented
> "other contributors" covers all the other groups of people that contribute to Solidus, and so I believe we only need to update the dates on the existing license. Spree Commerce Inc. (if the entity even still exists) retains the copyright of their contributions that still exist in the project.
> 
> 
> 
> ```
> 
> Copyright © 2007-2024, Spree Commerce Inc. and other contributors.
> 
> ```

Man, there's not much spree is doing better, but the license stuff definitely. 

As far as I understood some active companies are contributing (Nebulab, supergood,...) take some credit and put your label on it. It's FreeBSD license anyway. Surely Spree Inc can't have it for anything dating after the liquidation and nobody is gonna claim damages for anything as this software is free as a bird. 

![image](https://github.com/user-attachments/assets/da3be888-28e1-4824-b2d4-eab0bd29e33d)

2024-11-26 01:13 UTC, jarednorman commented
Alright, we should retain the existing license then and add an additional copyright line specifying that going forward that the copyright holders are the members of core and other contributors. Something like that.

2024-11-27 12:31 UTC, fthobe commented
> Alright, we should retain the existing license then and add an additional copyright line specifying that going forward that the copyright holders are the members of core and other contributors. Something like that.

Hey, 
given the profound IANAL Vibes here, we offered to Solidus core to split costs on having it vetted by a Lawyer and will do so this week, stay tuned :)

2024-11-27 16:58 UTC, jarednorman commented
Yes, we discussed that internally and everyone agreed that having a lawyer make the correct call for us here is the best course of action.

2024-12-02 14:47 UTC, fthobe commented
ok guys, 

- I spoke to the lawyer on friday and we are officially going to tackle this within the next weeks regarding the spree BSD license

- Regarding the included 3rd party assets we can tackle them in three ways: 

1. Boilerplate License inside the code 
2. Separate license file with the 3rd party code 
3. Integrated into the license.md file

I have a strong preference for cumulative license.md files, but I understand diverging preferences. 

Do we have anything apart from the icons and tailwind that needs to be licensed separately? 

**Missing Licenses**
- [ ] Tailwind
- [ ] Icons
- [ ] Fonts

2025-03-02 19:18 UTC, closed without merging